# Generated by Django 3.2.23 on 2023-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='abbreviations',
            field=models.TextField(default='default-abbreviations'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
    ]
