# Generated by Django 3.2.23 on 2024-01-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0002_auto_20231203_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='abbreviations',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='difficulty_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
