# Generated by Django 3.2.23 on 2024-01-14 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patterns', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500),
        ),
    ]
