# Generated by Django 3.2.23 on 2024-01-15 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patterns', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattern',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_pattern', to=settings.AUTH_USER_MODEL),
        ),
    ]
